version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:80"
    restart: always
    env_file:
      - ./client/.env
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "5050:5050"
    restart: always
    env_file:
      - ./server/.env
    networks:
      - app-network

  genintegrate:
    build: ./GemIntegrate
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - ./GemIntegrate/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
