version: '3'
services:
  client:
    image: amey12345/exposeitt-client:latest
    ports:
      - "3000:80"
    restart: always
    env_file:
      - ./client/.env
    networks:
      - app-network

  server:
    image: amey12345/exposeitt-server:latest
    ports:
      - "5050:5050"
    restart: always
    env_file:
      - ./server/.env
    networks:
      - app-network

  genintegrate:
    image: amey12345/exposeitt-gemintegrate:latest
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - ./GemIntegrate/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
